pipeline {
    agent { label 'signupage' }

    environment {
        CI = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Cloning repository..."
                git branch: 'signupage', url: 'https://github.com/lusungu-skillset/EduVibe.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    docker.image('node:18').inside('-u root') {
                        sh 'npm ci'
                    }
                }
            }
        }

        stage('Lint Check') {
            steps {
                script {
                    docker.image('node:18').inside('-u root') {
                        sh 'npx eslint src --ext .js,.jsx || true'
                    }
                }
            }
        }

        stage('Build React App') {
            steps {
                script {
                    docker.image('node:18').inside('-u root') {
                        sh 'npm run build'
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Build passed for SignUp component — good luck!"
        }
        failure {
            echo "Build failed — check logs."
        }
    }
}
