pipeline {
    agent { label 'eduvibe-agent' }

    environment {
        NODE_ENV = 'production'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

     stage('Install & Build') {
    steps {
        nodejs(nodeJSInstallationName: 'Node20') {
            dir('eduvibe') {   
                sh 'node -v'
                sh 'npm -v'
                sh 'npm ci'
                sh 'npm run build'
            }
        }
    }
}
    }

    post {
        always {
            echo 'Cleaning up workspace'
            deleteDir()
        }
        success {
            echo '✅ Build and lint successful!'
        }
        failure {
            echo '❌ Build or lint failed!'
        }
    }
}
